<?php
/**
 * GooglePlusOne plugin for Magento 
 *
 * @category    design_default
 * @package     Yireo_GooglePlusOne
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2010 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */
?>
<?php if($this->getConfig('active')) : ?>
    <div class="googleplusone">
    <?php if($this->getConfig('pagetype') == 'html5') : ?>
        <div class="g-plusone"<?php echo $this->getArguments(); ?>></div>
    <?php else: ?>
        <g:plusone<?php echo $this->getArguments(); ?>></g:plusone>
    <?php endif; ?>
    </div>
<?php endif; ?>
